# Generated by Django 5.2 on 2025-06-05 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
    ]
